### ISSUE TITLE
error when running hardhat compile in 0.4.58

### ISSUE THREAD

**Issue by nuno-add3** [OpenZeppelin/solidity-ast#51]
`
TypeError: child.findLast is not a function
    at deref (/home/ec2-user/apps/blockchain-dev/node_modules/solidity-ast/src/ast-dereferencer.ts:45:58)
    at derefNode (/home/ec2-user/apps/blockchain-dev/node_modules/solidity-ast/src/ast-dereferencer.ts:86:12)
    at curried (/home/ec2-user/apps/blockchain-dev/node_modules/solidity-ast/src/ast-dereferencer.ts:107:14)
    at tryDerefFunction (/home/ec2-user/apps/blockchain-dev/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:461:12)
    at getReferencedFunctionOpcodeErrors (/home/ec2-user/apps/blockchain-dev/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:435:30)
    at getReferencedFunctionOpcodeErrors.next (<anonymous>)
    at getFunctionOpcodeErrors (/home/ec2-user/apps/blockchain-dev/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:394:12)
    at getFunctionOpcodeErrors.next (<anonymous>)
    at getContractOpcodeErrors (/home/ec2-user/apps/blockchain-dev/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:370:10)
    at getContractOpcodeErrors.next (<anonymous>)
`
Reverting back to version 0.4.56 allow again the compilation.

**Comment by frangio** [comment]
This is a TypeScript configuration error. Please share your tsconfig.json.

**Comment by nuno-add3** [comment]
Yes but it's not my project using typescript. I'm using plain js in this project.
This happens when I run npx hardhat compile

**Comment by frangio** [comment]
Are you able to share the project so I can debug it?

**Comment by nuno-add3** [comment]
I can't as it's a private company repository.
But here are the dependencies (they use ts)
`
add3-blockchain@1.0.0 /opt/add3-blockchain
└─┬ @openzeppelin/hardhat-upgrades@3.2.1
  └─┬ @openzeppelin/upgrades-core@1.37.0
    └── solidity-ast@0.4.58
`

Also it seems a compiler incompatibility
![image](https://github.com/user-attachments/assets/646c408d-0e4b-4268-8956-ab619841af4e)

**Comment by frangio** [comment]
What version of Node.js are you using?

**Comment by nuno-add3** [comment]
v16.17.1

**Comment by frangio** [comment]
Node 16 is [End-of-Life since October 2023](https://github.com/nodejs/release?tab=readme-ov-file#end-of-life-releases) so we do not support it any more. Please use at least Node v18.

**Comment by nuno-add3** [comment]
Would be great if you could add that restriction in an "engine" item inside package.json.
Thanks for your support
